site_name: Pooja Devan
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Montserrat
    code: Red Hat Mono
    
  icon:
    logo: fontawesome/solid/pen-fancy

  favicon: Images/Pen.png 

 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Dark mode
      primary: teal
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: teal
      accent: deep purple

  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - My Career Map: index.md
  - Material for Mkdocs: Codex.md
  - Git for Technical Writers: gitdc.md
  - Explore: Explore.md




 



